# Numpy

## No Numpy

In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

In [2]:
ab = []
for i in range(len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

## With Numpy

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

## Create a Numpy array

In [5]:
import numpy as np

In [6]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
a = np.array([2,3.12,4,5.8])
a

array([2.  , 3.12, 4.  , 5.8 ])

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([1.1,2.4,5,8,9.6], dtype = "int")
b

array([1, 2, 5, 8, 9])

## create an array from scratch

In [11]:
import numpy as np

In [14]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Array sorting

In [1]:
import numpy as np

In [2]:
a = np.array([2,1,3,7,5,9,8])

In [6]:
np.sort(a)
a

array([1, 2, 3, 5, 7, 8, 9])

In [7]:
# iki boyutlu

In [17]:
b = np.random.randint(10, size = (3,3))
b

array([[1, 2, 2],
       [1, 0, 9],
       [5, 0, 5]])

In [19]:
np.sort(b, axis=1)
b

array([[1, 2, 2],
       [1, 0, 9],
       [5, 0, 5]])

In [24]:
np.random.normal(10, size=(3,4))

array([[10.9129025 ,  9.95176275,  9.39203716, 11.19794779],
       [ 9.93932688,  9.66906642, 10.76191004,  9.7029268 ],
       [ 9.43215036, 10.5791203 ,  8.70413948,  9.15293115]])

## Fancy Index

In [1]:
import numpy as np

In [4]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
print("v1 : ",v[1])
print("v3 : ",v[3])
print("v5 : ",v[5])

v1 :  3
v3 :  9
v5 :  15


In [9]:
al_getir = [1,3,5]
v[al_getir]

array([ 3,  9, 15])

## conditional element operations

In [10]:
import numpy as np

In [12]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [13]:
v[v<3]

array([1, 2])

In [14]:
v[v>=3]

array([3, 4, 5])

In [15]:
v*2

array([ 2,  4,  6,  8, 10])

In [16]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

## solving equation with 2 unknowns with numpy

* **5 * x0 + x1 = 12** 
* **x0 + 3 * x1 = 10**

In [17]:
import numpy as np

In [29]:
a = np.array([[5,1],[1,3]])
a

array([[5, 1],
       [1, 3]])

In [32]:
b = np.array([12,10])
b

array([12, 10])

In [34]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

In [40]:
"""2x - y = 1
x - 2y = 4"""


'2x - y = 1\nx - 2y = 4'

In [37]:
a = np.array([[2,-1],[1,-2]])
a

array([[ 2, -1],
       [ 1, -2]])

In [38]:
b = np.array([1,4])
b

array([1, 4])

In [39]:
np.linalg.solve(a,b)

array([-0.66666667, -2.33333333])